dependencies:
- type: olm.gvk
  value:
    group: nfd.openshift.io
    kind: NodeFeatureDiscovery
    version: v1
#- type: olm.gvk
#  value:
#    group: console.openshift.io
#    kind: ConsolePlugin
#    version: v1alpha1
